

# FROM node:18.14.0-alpine As development

# WORKDIR /usr/src/app
# # WORKDIR /app

# COPY package*.json ./

# RUN npm install --force --only=development
# # RUN npm install --force 

# COPY . .

# RUN npm run build

# FROM node:18.14.0-alpine as production

# ARG NODE_ENV=dev
# ENV NODE_ENV=${NODE_ENV}

# WORKDIR /usr/src/app
# # WORKDIR /app

# COPY package*.json ./

# RUN npm install --force --only=production
# # RUN npm install --force

# COPY . .



# COPY --from=development /usr/src/app/dist ./dist
# # COPY --from=development /app/dist ./dist

# # EXPOSE 8080

# CMD ["npm", "run","start:dev"]


FROM node:18.15.0-alpine

WORKDIR /usr/src/app

COPY package.json ./

# RUN npm i -g @nestjs/cli

RUN npm install --force

COPY ./ ./

CMD [ "npm", "run", "start:dev" ]