version: '3'
services:
  redis-server-dev:
    image: redis
    container_name: redis-server-dev
    hostname: redis-server-dev
    ports:
      - '6379:6379'

  lattice-api-server-dev:
    build: 
      dockerfile: ./Dockerfile.dev
      context: .
    ports:
      - "5555:3005"
    volumes:
      - /usr/src/app/node_modules
      - ./:/usr/src/app