version: '3'
services:
  redis-server:
    image: redis
    container_name: redis-server
    hostname: redis-server
    ports:
      - '6379:6379'

  lattice-api-server:
    build: 
      context: .    # 꼭붙여주기. 무조건.
      dockerfile: ./Dockerfile
    ports:
      - "5555:3005"
    volumes:
      - .:/app