const constantString = {
  morningeeConnection: 'MORNINGEE_CONNECTION',
  portfolioRepository: 'PORTFOLIO_REPOSITORY',
  portfolioTableName: 'portfolio',
  acUserTableName: 'ac_user',
  AC_USER_JWT_ACCESS_NAME: 'acUserAccessToken',
  AC_USER_JWT_REFRESH_NAME: 'acUserRefreshToken',
  AC_USER_JWT_ACCESS_EXPIRATION_TIME: 1 * 60 * 60, // 초(second)단위. 60분 = 한시간
  AC_USER_JWT_REFRESH_EXPIRATION_TIME: 1 * 60 * 60 * 48, // 2일
  MASTER_USER_JWT_ACCESS_NAME: 'masterUserAccessToken',
  MASTER_USER_JWT_REFRESH_NAME: 'masterUserRefreshToken',
  MASTER_USER_JWT_ACCESS_EXPIRATION_TIME: '1h',
  MASTER_USER_JWT_REFRESH_EXPIRATION_TIME: '2h',
  KTC_PLAN_START_TIME_HOUR: 7, // ktc (UTC + 9시간)
  KTC_PLAN_START_TIME_MINUTE: 0,
  KTC_PLAN_END_TIME_HOUR: 9, // ktc (UTC + 9)
  KTC_PLAN_END_TIME_MINUTE: 0,
  KTC_PLAN_HALF_SUCCESS_TIME_HOUR: 12, // ktc (UTC + 9)
  KTC_PLAN_HAL_SUCCESS_TIME_MINUTE: 0,
  UTC_PLAN_START_TIME_HOUR: 22,
  UTC_PLAN_START_TIME_MINUTE: 0,
  UTC_PLAN_END_TIME_HOUR: 0,
  UTC_PLAN_END_TIME_MINUTE: 0,
  UTC_PLAN_HALF_SUCCESS_END_HOUR: 3, // SUCCESS_END_TIME이 지나고, 중간성공이라도 하기 위해 이 시간안에 작성해야함.
  UTC_PLAN_HALF_SUCCESS_END_MINUTE: 0,
};

const errorString = {
  NOT_EDITABLE_TIME: 'NOT_EDITABLE_TIME',
  DUPLICATE_CREATION_TIME: 'DUPLICATE_CREATION_TIME',
  REFRESH_TOKEN_ERROR: 'REFRESH_TOKEN_ERROR',
  ACCESS_TOKEN_ERROR: 'ACCESS_TOKEN_ERROR',
};

export { constantString, errorString };
